### ISSUE TITLE
Fuse-forge doesn't work with Forge 3.5.1.Final

### ISSUE THREAD

**Issue by dsimansk** [jboss-fuse/fuse-forge#16]
Fuse-forge version 1.0.1 doesn't work on latest release of JBoss Forge 3.5.1.Final. There is an exception in Forge's log and error displayed in console. Worked fine with previous version 3.5.0.Final.

```
17:55:02,478 SEVERE [org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator] (AeshProcess: 1) Error while navigating to next step: java.lang.IllegalStateException
	at java.util.Optional.orElseThrow(Optional.java:290) [rt.jar:1.8.0_101]
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.getLatestCatalogVersion(FuseProjectSetupStep.java:299)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.configureCatalogVersionInput(FuseProjectSetupStep.java:204)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.initializeUI(FuseProjectSetupStep.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_101]
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87) [furnace-proxy-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42) [furnace-api-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103) [furnace-proxy-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep_$$_javassist_08f3ee6e-1985-456b-a20d-7dfc92e8c236.initializeUI(FuseProjectSetupStep_$$_javassist_08f3ee6e-1985-456b-a20d-7dfc92e8c236.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.initialize(WizardCommandControllerImpl.java:121)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.canMoveToNextStep(NoUIWizardControllerDecorator.java:59)
	at org.jboss.forge.addon.shell.aesh.ShellWizard.populate(ShellWizard.java:81)
	at org.jboss.forge.addon.shell.aesh.ShellWizard.getParser(ShellWizard.java:46)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandRegistry.getForgeCommand(ForgeCommandRegistry.java:124)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandRegistry.getCommand(ForgeCommandRegistry.java:90)
	at org.jboss.aesh.console.AeshConsoleImpl.getCommand(AeshConsoleImpl.java:247)
	at org.jboss.aesh.console.AeshConsoleImpl.access$100(AeshConsoleImpl.java:62)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:308)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_101]

17:55:02,493 SEVERE [org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator] (AeshProcess: 1) Error while navigating to next step: java.lang.IllegalStateException
	at java.util.Optional.orElseThrow(Optional.java:290) [rt.jar:1.8.0_101]
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.getLatestCatalogVersion(FuseProjectSetupStep.java:299)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.configureCatalogVersionInput(FuseProjectSetupStep.java:204)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.initializeUI(FuseProjectSetupStep.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_101]
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87) [furnace-proxy-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42) [furnace-api-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103) [furnace-proxy-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep_$$_javassist_08f3ee6e-1985-456b-a20d-7dfc92e8c236.initializeUI(FuseProjectSetupStep_$$_javassist_08f3ee6e-1985-456b-a20d-7dfc92e8c236.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.next(WizardCommandControllerImpl.java:391)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.canMoveToNextStep(NoUIWizardControllerDecorator.java:59)
	at org.jboss.forge.addon.shell.aesh.ShellWizard.promptRequiredMissingValues(ShellWizard.java:110)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:65)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_101]

17:55:02,504 SEVERE [org.jboss.forge.addon.shell.aesh.CommandAdapter] (AeshProcess: 1) Failed to execute [project-new] due to exception.: java.lang.IllegalStateException: Error while moving to the next wizard step
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:107)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.canExecute(WizardCommandControllerImpl.java:319)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:135)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:151)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_101]
Caused by: java.lang.IllegalStateException
	at java.util.Optional.orElseThrow(Optional.java:290) [rt.jar:1.8.0_101]
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.getLatestCatalogVersion(FuseProjectSetupStep.java:299)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.configureCatalogVersionInput(FuseProjectSetupStep.java:204)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.initializeUI(FuseProjectSetupStep.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_101]
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87) [furnace-proxy-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42) [furnace-api-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103) [furnace-proxy-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep_$$_javassist_08f3ee6e-1985-456b-a20d-7dfc92e8c236.initializeUI(FuseProjectSetupStep_$$_javassist_08f3ee6e-1985-456b-a20d-7dfc92e8c236.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.next(WizardCommandControllerImpl.java:391)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:103)
	... 10 more

17:55:02,506 SEVERE [org.jboss.forge.addon.shell.aesh.CommandAdapter] (AeshProcess: 1) Error while moving to the next wizard step: java.lang.IllegalStateException: Error while moving to the next wizard step
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:107)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.canExecute(WizardCommandControllerImpl.java:319)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:135)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:151)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_101]
Caused by: java.lang.IllegalStateException
	at java.util.Optional.orElseThrow(Optional.java:290) [rt.jar:1.8.0_101]
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.getLatestCatalogVersion(FuseProjectSetupStep.java:299)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.configureCatalogVersionInput(FuseProjectSetupStep.java:204)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.initializeUI(FuseProjectSetupStep.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_101]
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87) [furnace-proxy-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42) [furnace-api-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103) [furnace-proxy-2.25.2.Final.jar:2.25.2.Final]
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep_$$_javassist_08f3ee6e-1985-456b-a20d-7dfc92e8c236.initializeUI(FuseProjectSetupStep_$$_javassist_08f3ee6e-1985-456b-a20d-7dfc92e8c236.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.next(WizardCommandControllerImpl.java:391)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:103)
	... 10 more
```

**Comment by dhirajsb** [comment]
Closing stale issue.
