### ISSUE TITLE
fuse-forge 1.0.1 does not work with Forge 3.9.1.Final -- Missing maven artifact

### ISSUE THREAD

**Issue by tsedmik** [jboss-fuse/fuse-forge#20]
If I try to create a new Fuse project via fuse-forge addon in Forge, I get the following error.
```
[tmp]$ project-new
***INFO*** Required inputs not satisfied, entering interactive mode
* Project name:  test
? Top level package [org.test]:  
? Version [1.0.0-SNAPSHOT]:  
? Final name:  
? Project location [/home/tsedmik/devel/git/jbds-installer/devstudio-12.9.0.GA/target/tmp]:  
? Use Target Location Root? (If specified, it won't create a subdirectory inside the specified Project location) [y/N]: 

[0] (x) war
[1] ( ) fuse
[2] ( ) jar
[3] ( ) parent
[4] ( ) forge-addon
[5] ( ) resource-jar
[6] ( ) ear
[7] ( ) from-archetype
[8] ( ) generic

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Project type: [0-8] 1

[0] (x) Maven

Press <ENTER> to confirm, or <CTRL>+C to cancel.
* Build system: [0] 
***ERROR*** Error while moving to the next wizard step
```
The log reveals that the issue is in finding ***io.fabric8.archetypes:archetypes-catalog:jar:2.2.195.redhat-000026*** Maven artefact.
```
Jan 24, 2019 11:44:45 AM org.jboss.forge.addon.shell.aesh.CommandAdapter displayResult
SEVERE: Error while moving to the next wizard step
java.lang.IllegalStateException: Error while moving to the next wizard step
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:114)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.canExecute(WizardCommandControllerImpl.java:326)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:142)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:157)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.forge.furnace.manager.maven.MavenOperationException: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find io.fabric8.archetypes:archetypes-catalog:jar:2.2.195.redhat-000026 in http://fuse-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/repository/jbdsis-qe/ was cached in the local repository, resolution will not be reattempted until the update interval of internal-repository has elapsed or updates are forced
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver.resolveArtifact(MavenDependencyResolver.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver_$$_jvst183_50.resolveArtifact(MavenDependencyResolver_$$_jvst183_50.java)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.getCatalog(FuseProjectSetupStep.java:274)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.configureArchetypeInput(FuseProjectSetupStep.java:236)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep.initializeUI(FuseProjectSetupStep.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.fuse.forge.addon.ui.FuseProjectSetupStep_$$_jvst183_65.initializeUI(FuseProjectSetupStep_$$_jvst183_65.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.next(WizardCommandControllerImpl.java:398)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:110)
	... 10 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find io.fabric8.archetypes:archetypes-catalog:jar:2.2.195.redhat-000026 in http://fuse-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/repository/jbdsis-qe/ was cached in the local repository, resolution will not be reattempted until the update interval of internal-repository has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:260)
	at org.jboss.forge.addon.maven.dependencies.MavenDependencyResolver.resolveArtifact(MavenDependencyResolver.java:191)
	... 32 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find io.fabric8.archetypes:archetypes-catalog:jar:2.2.195.redhat-000026 in http://fuse-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/repository/jbdsis-qe/ was cached in the local repository, resolution will not be reattempted until the update interval of internal-repository has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:233)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:208)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:563)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:481)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	... 36 more
```

**Comment by tsedmik** [comment]
I do not encounter this issue any more --> closing
